###################################################
# +---------------------------------------------+ #
# |               Chat Features                 | #
# +---------------------------------------------+ #
###################################################

# Options for toggling on or off.

features:
  - tabprefix
  - tabnation
  - tabtown
  - chatgames

###################################################
# +---------------------------------------------+ #
# |                 Gradients                   | #
# +---------------------------------------------+ #
###################################################

Presets:
  # Pre-configured gradients that can be equipped with an alias rather than typing out the hexes.
  # #hex1:#hex2:#hex3....
  rainbow: "#e07870:#e0aa70:#e3de84:#a3e391:#8de0c1:#8fd2e3:#938de0:#c491e3"
  dragonfruit: "#ff2c2c:#ff005d:#ff008f:#ff2dc3:#ff57f5"
  jshine: "#12c2e9:#c471ed:#f64f59"
  eveningsunshine: "#b92b27:#1565C0"
  metapolis: "#659999:#f4791f"
  kyoopal: "#dd3e54:#6be585"
  kyemeh: "#8360c3:#2ebf91"
  wiretap: "#8A2387:#E94057:#F27121"
  magic: "#59C173:#a17fe0:#5D26C1"
  redsunset: "#355C7D:#6C5B7B:#C06C84"

###################################################
# +---------------------------------------------+ #
# |                  Messages                   | #
# +---------------------------------------------+ #
###################################################

# System messages

messages:
  prefix: '<bold><red>U</red><white>L</white></bold> Chat <dark_gray>» '
  chat-toggle-command: '<yellow>Use /chat [Chat Feature] on/off'
  toggled-feature: '<feature> successfully set to <toggle>!'
  invalid-feature: '<red>Invalid feature.'
  reset: '<green>UnitedChat settings reset.'
  no-perm: '<red>You don''t have permission to use this command.'

# +---------------------------------------------+ #
# |               Join Messages                 | #
# +---------------------------------------------+ #

  motd:
    - '<gradient:#ffffff:#ff5555>------------------------------</gradient>'
    - '                     <bold><red>UNITED</red><white>LANDS</white></bold>'
    - '                <red>Welcome back <yellow><italic>%player_name%</italic><red>!'
    - '    <red>There are currently <white>%server_online% <red>players online.'
    - '<gradient:#ffffff:#ff5555>------------------------------</gradient>'
  first-join-motd:
    - '<gradient:#ffffff:#ff5555>------------------------------</gradient>'
    - '                     <red><bold>UNITED<white><bold>LANDS     '
    - '             <red>Welcome to <red><bold>United<white><bold>Lands <yellow><italic>%player_name%&c!'
    - '    <red>There are currently <white>%server_online% <red>players online.'
    - '<gradient:#ffffff:#ff5555>------------------------------</gradient>'

# +---------------------------------------------+ #
# |               War Messages                  | #
# +---------------------------------------------+ #

  gradient-changed: '<green>Gradient changed.'
  gradient-on: '<green>Gradient enabled.'
  gradient-command: '<yellow>Use /gradient [toggle] | [preset] | [hexcolor1] [hexcolor2] %player_name%'
  gradient-set-command: '<yellow>Please provide a preset name or a custom hex color gradient (#RRGGBB:#RRGGBB:#RRGGBB...)'
  gradient-admin-command: '<yellow>Use /gradient [toggle] | [preset] | [hexcolor1] [hexcolor] |[player]'
  gradient-off: '<red>Gradient disabled.'
  gradient-unknown-preset: '<red>Preset not recognized.'
  gradient-is-off: '<red>Your gradient is disabled.'
  gradient-is-on: '<red>Your gradient is enabled.'
  current-gradient: '<red>Your current gradient is: <gradient>'
  no-perm-gradient: '<red>You don''t have permission to set a custom hex color gradient.'
  invalid-gradient: "<red>Couldn't find a gradient preset matching this name."